name: Keep Render App Awake

on:
  schedule:
    - cron: "*/14 * * * *"  # every 14 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: curl https://instasend.onrender.com/api/ping
